"""
Farm management routes
"""
from flask import Blueprint, render_template, request, redirect, url_for, session, flash, jsonify
from app import db
import json as json_module
import os
import math
from app.models.user import User
from app.models.farm import Farm
from app.models.crop import Crop
from app.models.livestock import Livestock
from functools import wraps
from datetime import datetime
import logging

# Path to the pre-generated barangay GeoJSON (generated by generate_barangays.py)
_BARANGAY_GEOJSON_PATH = os.path.join(os.path.dirname(__file__), '..', 'static', 'victoria_barangays.json')
_barangay_cache = None  # in-memory cache so we read the file only once

# Configure logging
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)

farm_bp = Blueprint('farm', __name__, url_prefix='/farm')

# List of Victoria barangays
VICTORIA_BARANGAYS = {
    1: 'Banca-Banca',
    2: 'Daniw',
    3: 'Masapang',
    4: 'Nanhaya',
    5: 'Pagalangan',
    6: 'San Benito',
    7: 'San Felix',
    8: 'San Francisco',
    9: 'San Roque'
}


def _polygon_centroid(coords):
    """Return centroid [lat, lng] from a polygon ring [ [lng,lat], ... ]."""
    if not coords or len(coords) < 3:
        return None

    # Ensure closed ring for area formula
    pts = coords[:]
    if pts[0] != pts[-1]:
        pts.append(pts[0])

    area2 = 0.0
    cx = 0.0
    cy = 0.0
    for i in range(len(pts) - 1):
        x0, y0 = pts[i][0], pts[i][1]
        x1, y1 = pts[i + 1][0], pts[i + 1][1]
        cross = (x0 * y1) - (x1 * y0)
        area2 += cross
        cx += (x0 + x1) * cross
        cy += (y0 + y1) * cross

    if abs(area2) < 1e-12:
        lats = [p[1] for p in coords]
        lngs = [p[0] for p in coords]
        return [sum(lats) / len(lats), sum(lngs) / len(lngs)]

    area = area2 / 2.0
    cx = cx / (6.0 * area)
    cy = cy / (6.0 * area)
    return [cy, cx]


def _ring_area_sqm(ring):
    """Approximate ring area in square meters using local projection + shoelace."""
    if not ring or len(ring) < 3:
        return 0.0

    points = ring[:]
    if points[0] == points[-1]:
        points = points[:-1]
    if len(points) < 3:
        return 0.0

    lat0 = sum(p[1] for p in points) / len(points)
    lat0_rad = math.radians(lat0)
    earth_radius = 6378137.0

    xy = []
    for lng, lat in points:
        x = earth_radius * math.radians(lng) * math.cos(lat0_rad)
        y = earth_radius * math.radians(lat)
        xy.append((x, y))

    area2 = 0.0
    for i in range(len(xy)):
        x1, y1 = xy[i]
        x2, y2 = xy[(i + 1) % len(xy)]
        area2 += (x1 * y2) - (x2 * y1)
    return abs(area2) / 2.0


def _geometry_area_sqm(geom):
    """Return area in square meters for Polygon/MultiPolygon GeoJSON geometry."""
    if not geom:
        return 0.0

    gtype = geom.get('type')
    coords = geom.get('coordinates', [])

    if gtype == 'Polygon':
        if not coords:
            return 0.0
        outer = _ring_area_sqm(coords[0])
        holes = sum(_ring_area_sqm(r) for r in coords[1:])
        return max(0.0, outer - holes)

    if gtype == 'MultiPolygon':
        total = 0.0
        for poly in coords:
            if not poly:
                continue
            outer = _ring_area_sqm(poly[0])
            holes = sum(_ring_area_sqm(r) for r in poly[1:])
            total += max(0.0, outer - holes)
        return total

    return 0.0


def _parse_lot_boundary(raw_boundary):
    """Validate and normalize polygon/multipolygon GeoJSON string."""
    if not raw_boundary:
        return None, None

    try:
        geom = json_module.loads(raw_boundary)
    except Exception:
        return None, 'Invalid lot boundary format.'

    if not isinstance(geom, dict) or 'type' not in geom or 'coordinates' not in geom:
        return None, 'Lot boundary must be valid GeoJSON geometry.'

    gtype = geom.get('type')
    coords = geom.get('coordinates')
    if gtype not in ('Polygon', 'MultiPolygon'):
        return None, 'Lot boundary only supports Polygon or MultiPolygon.'

    try:
        if gtype == 'Polygon':
            ring = coords[0]
            if len(ring) < 4:
                return None, 'Lot boundary polygon needs at least 3 points.'
        else:
            if not coords or not coords[0] or len(coords[0][0]) < 4:
                return None, 'Lot boundary multipolygon needs at least 3 points.'
    except Exception:
        return None, 'Invalid lot boundary coordinates.'

    return geom, None


def _to_title_case(value):
    """Normalize text to title case while collapsing extra spaces."""
    cleaned = ' '.join((value or '').split())
    return cleaned.title()

def login_required(f):
    """Decorator to require login"""
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'user_id' not in session:
            flash('Please login first', 'warning')
            return redirect(url_for('auth.login'))
        return f(*args, **kwargs)
    return decorated_function

@farm_bp.route('/', methods=['GET'])
@login_required
def list_farms():
    """List farms with role-based and custom filtering"""
    try:
        logger.info(f"[LIST_FARMS] User {session.get('user_id')} accessing farms")
        
        user = User.query.get(session['user_id'])
        
        if not user:
            logger.error(f"[LIST_FARMS] User not found: {session.get('user_id')}")
            flash('User not found', 'error')
            return redirect(url_for('auth.login'))
        
        logger.info(f"[LIST_FARMS] User role: {user.role}, barangay: {user.barangay_name}")
        
        # Filter based on user role
        if user.role == 'farmer':
            # Farmers see only their own farms
            query = Farm.query.filter_by(owner_id=user.id, is_active=True)
            logger.info(f"[LIST_FARMS] Farmer {user.id} filtering own farms")
        else:
            # Admins see all farms
            query = Farm.query.filter_by(is_active=True)
            logger.info(f"[LIST_FARMS] Admin/Coordinator {user.id} filtering all farms")
        
        # Get search and filter parameters from request
        search_query = request.args.get('search', '').strip()
        barangay_filter = request.args.get('barangay', '')
        crop_type_filter = request.args.get('crop_type', '')
        animal_type_filter = request.args.get('animal_type', '')
        page = request.args.get('page', 1, type=int)
        per_page = 20
        
        # Apply search filter
        if search_query:
            query = query.filter(
                db.or_(
                    Farm.name.ilike(f'%{search_query}%'),
                    Farm.description.ilike(f'%{search_query}%')
                )
            )
            logger.info(f"[LIST_FARMS] Applied search filter: {search_query}")
        
        # Apply additional filters
        if barangay_filter and barangay_filter != '':
            query = query.filter_by(barangay_name=barangay_filter)
            logger.info(f"[LIST_FARMS] Applied barangay filter: {barangay_filter}")
        
        if crop_type_filter and crop_type_filter != '':
            # Filter farms that have crops with this crop_type
            query = query.join(Crop).filter(Crop.crop_type == crop_type_filter).distinct()
            logger.info(f"[LIST_FARMS] Applied crop_type filter: {crop_type_filter}")
        
        # Apply livestock type filter via subquery before paginating
        if animal_type_filter and animal_type_filter != '':
            from sqlalchemy import exists
            query = query.filter(
                exists().where(
                    (Livestock.farm_id == Farm.id) &
                    (Livestock.animal_type == animal_type_filter)
                )
            )
            logger.info(f"[LIST_FARMS] Applied animal_type filter: {animal_type_filter}")

        pagination = query.order_by(Farm.created_at.desc()).paginate(page=page, per_page=per_page, error_out=False)
        farms = pagination.items
        logger.info(f"[LIST_FARMS] Successfully loaded {len(farms)} farms (page {page}/{pagination.pages})")
        
        # Get available filter options for the template
        # Get all unique barangays - always show all Victoria barangays for admin/coordinator
        if user.role == 'farmer':
            barangay_options = sorted(list({
                f.barangay_name for f in Farm.query.filter_by(owner_id=user.id, is_active=True).with_entities(Farm.barangay_name).distinct()
                    if f.barangay_name
            }))
        else:
            # Admin - show all Victoria barangays
            barangay_options = sorted(list(VICTORIA_BARANGAYS.values()))
        
        # Get all unique crop types from Crop model
        if user.role == 'farmer':
            crop_query = db.session.query(Crop.crop_type).join(Farm).filter(Farm.owner_id == user.id, Farm.is_active == True).distinct()
        else:
            crop_query = db.session.query(Crop.crop_type).join(Farm).filter(Farm.is_active == True).distinct()
        crop_options = sorted([c[0] for c in crop_query.all()])
        
        # Get all unique animal types from livestock
        if user.role == 'farmer':
            animal_query = db.session.query(Livestock.animal_type).join(Farm).filter_by(owner_id=user.id, is_active=True).distinct()
        else:
            animal_query = db.session.query(Livestock.animal_type).join(Farm).filter(Farm.is_active == True).distinct()
        animal_options = sorted([a[0] for a in animal_query.all()])
        
        # Use role-specific template
        if user.role == 'farmer':
            return render_template('farm/farmer_list.html', farms=farms, user=user,
                                 pagination=pagination,
                                 barangay_options=barangay_options, crop_options=crop_options,
                                 animal_options=animal_options, active_barangay=barangay_filter,
                                 active_crop=crop_type_filter, active_animal=animal_type_filter,
                                 search_query=search_query)
        else:
            return render_template('farm/list.html', farms=farms, user=user,
                                 pagination=pagination,
                                 barangay_options=barangay_options, crop_options=crop_options,
                                 animal_options=animal_options, active_barangay=barangay_filter,
                                 active_crop=crop_type_filter, active_animal=animal_type_filter,
                                 search_query=search_query)
        
    except Exception as e:
        logger.error(f"[LIST_FARMS] ERROR: {str(e)}", exc_info=True)
        flash(f'Error loading farms: {str(e)}', 'error')
        return redirect(url_for('dashboard.index'))

@farm_bp.route('/create', methods=['GET', 'POST'])
@login_required
def create_farm():
    """Create a new farm"""
    try:
        logger.info(f"[CREATE_FARM] User {session.get('user_id')} accessing create farm")
        
        user = User.query.get(session['user_id'])
        
        if not user:
            logger.error(f"[CREATE_FARM] User not found: {session.get('user_id')}")
            flash('User not found', 'error')
            return redirect(url_for('auth.login'))
        
        # Only farmers can create farms
        if user.role != 'farmer':
            logger.warning(f"[CREATE_FARM] Non-farmer {user.id} tried to create farm (role: {user.role})")
            flash('Only farmers can create farms', 'error')
            return redirect(url_for('farm.list_farms'))
        
        if request.method == 'POST':
            try:
                name = _to_title_case(request.form.get('name', ''))
                crop_type = request.form.get('crop_type', '').strip()
                area_square_meters = request.form.get('area_square_meters', '0')
                description = request.form.get('description', '').strip()
                latitude = request.form.get('latitude', '')
                longitude = request.form.get('longitude', '')
                lot_boundary_raw = request.form.get('lot_boundary_geojson', '').strip()
                
                logger.info(f"[CREATE_FARM] Form data - name: {name}, crop: {crop_type}, area: {area_square_meters}")
                
                barangay_name = request.form.get('barangay_name', '').strip()
                barangay_id = next((k for k, v in VICTORIA_BARANGAYS.items() if v == barangay_name), user.barangay_id)

                # Validation
                if not name:
                    flash('Farm name is required', 'error')
                elif not crop_type:
                    flash('Crop type is required', 'error')
                elif not barangay_name:
                    flash('Barangay is required', 'error')
                else:
                    try:
                        lot_boundary, boundary_error = _parse_lot_boundary(lot_boundary_raw)
                        if boundary_error:
                            flash(boundary_error, 'error')
                            return render_template('farm/create.html', user=user, barangay=user.barangay_name, victoria_barangays=VICTORIA_BARANGAYS)

                        if lot_boundary:
                            area = _geometry_area_sqm(lot_boundary)
                            if area <= 0:
                                flash('Unable to calculate lot area from boundary. Please redraw the shape.', 'error')
                                return render_template('farm/create.html', user=user, barangay=user.barangay_name, victoria_barangays=VICTORIA_BARANGAYS)
                        else:
                            area = float(area_square_meters)
                            if area <= 0:
                                flash('Area must be greater than 0', 'error')
                                return render_template('farm/create.html', user=user, barangay=user.barangay_name, victoria_barangays=VICTORIA_BARANGAYS)

                            # Create farm
                        farm = Farm(
                            name=name,
                            crop_type=crop_type,
                            area_square_meters=area,
                            description=description,
                            owner_id=user.id,
                            barangay_id=barangay_id,
                            barangay_name=barangay_name
                        )
                            
                        # Add coordinates if provided
                        if latitude:
                            try:
                                farm.latitude = float(latitude)
                            except ValueError:
                                logger.warning(f"[CREATE_FARM] Invalid latitude: {latitude}")

                        if longitude:
                            try:
                                farm.longitude = float(longitude)
                            except ValueError:
                                logger.warning(f"[CREATE_FARM] Invalid longitude: {longitude}")

                        if lot_boundary:
                            farm.lot_boundary_geojson = json_module.dumps(lot_boundary)
                            # If no pin provided, use boundary centroid as map anchor
                            if not farm.latitude or not farm.longitude:
                                if lot_boundary.get('type') == 'Polygon':
                                    center = _polygon_centroid(lot_boundary['coordinates'][0])
                                else:
                                    center = _polygon_centroid(lot_boundary['coordinates'][0][0])
                                if center:
                                    farm.latitude = center[0]
                                    farm.longitude = center[1]

                        db.session.add(farm)
                        db.session.commit()

                        logger.info(f"[CREATE_FARM] Farm created successfully - ID: {farm.id}, Owner: {user.id}")
                        flash(f'Farm "{name}" created successfully!', 'success')
                        return redirect(url_for('farm.list_farms'))
                            
                    except ValueError as e:
                        logger.error(f"[CREATE_FARM] ValueError: {str(e)}")
                        flash('Area must be a valid number', 'error')
                        
            except Exception as e:
                logger.error(f"[CREATE_FARM] POST ERROR: {str(e)}", exc_info=True)
                flash(f'Error creating farm: {str(e)}', 'error')
        
        return render_template('farm/create.html', user=user, barangay=user.barangay_name, victoria_barangays=VICTORIA_BARANGAYS)
        
    except Exception as e:
        logger.error(f"[CREATE_FARM] ERROR: {str(e)}", exc_info=True)
        flash(f'Error accessing create farm: {str(e)}', 'error')
        return redirect(url_for('farm.list_farms'))

@farm_bp.route('/<int:farm_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_farm(farm_id):
    """Edit a farm"""
    try:
        logger.info(f"[EDIT_FARM] User {session.get('user_id')} accessing farm {farm_id}")
        
        farm = Farm.query.get_or_404(farm_id)
        user = User.query.get(session['user_id'])
        
        if not user:
            logger.error(f"[EDIT_FARM] User not found: {session.get('user_id')}")
            flash('User not found', 'error')
            return redirect(url_for('auth.login'))
        
        # Only owner or admin can edit
        if user.id != farm.owner_id and user.role not in ['system_admin', 'victoria_admin']:
            logger.warning(f"[EDIT_FARM] Unauthorized edit attempt - User {user.id} trying to edit farm {farm_id} (owner: {farm.owner_id})")
            flash('You can only edit your own farms', 'error')
            return redirect(url_for('farm.list_farms'))
        
        if request.method == 'POST':
            try:
                farm.name = _to_title_case(request.form.get('name', ''))
                farm.crop_type = request.form.get('crop_type', '').strip()
                farm.description = request.form.get('description', '').strip()
                
                logger.info(f"[EDIT_FARM] Updating farm {farm_id}: {farm.name}")
                
                # Update barangay if changed
                new_barangay_name = request.form.get('barangay_name', '').strip()
                if new_barangay_name and new_barangay_name in VICTORIA_BARANGAYS.values():
                    farm.barangay_name = new_barangay_name
                    farm.barangay_id = next(k for k, v in VICTORIA_BARANGAYS.items() if v == new_barangay_name)

                # Update coordinates (empty string = clear the pin)
                latitude  = request.form.get('latitude',  '').strip()
                longitude = request.form.get('longitude', '').strip()
                lot_boundary_raw = request.form.get('lot_boundary_geojson', '').strip()

                lot_boundary, boundary_error = _parse_lot_boundary(lot_boundary_raw)
                if boundary_error:
                    flash(boundary_error, 'error')
                    return render_template('farm/edit.html', farm=farm, user=user, victoria_barangays=VICTORIA_BARANGAYS)

                if lot_boundary:
                    area = _geometry_area_sqm(lot_boundary)
                    if area <= 0:
                        flash('Unable to calculate lot area from boundary. Please redraw the shape.', 'error')
                        return render_template('farm/edit.html', farm=farm, user=user, victoria_barangays=VICTORIA_BARANGAYS)
                    farm.area_square_meters = area
                else:
                    try:
                        area = float(request.form.get('area_square_meters', farm.area_square_meters))
                        if area <= 0:
                            flash('Area must be greater than 0', 'error')
                            return render_template('farm/edit.html', farm=farm, user=user, victoria_barangays=VICTORIA_BARANGAYS)
                        farm.area_square_meters = area
                    except ValueError:
                        logger.error(f"[EDIT_FARM] Invalid area value")
                        flash('Area must be a valid number', 'error')
                        return render_template('farm/edit.html', farm=farm, user=user, victoria_barangays=VICTORIA_BARANGAYS)

                if latitude and longitude:
                    try:
                        farm.latitude  = float(latitude)
                        farm.longitude = float(longitude)
                    except ValueError:
                        logger.warning(f"[EDIT_FARM] Invalid coordinates: {latitude}, {longitude}")
                else:
                    farm.latitude  = None
                    farm.longitude = None

                if lot_boundary:
                    farm.lot_boundary_geojson = json_module.dumps(lot_boundary)
                    if not farm.latitude or not farm.longitude:
                        if lot_boundary.get('type') == 'Polygon':
                            center = _polygon_centroid(lot_boundary['coordinates'][0])
                        else:
                            center = _polygon_centroid(lot_boundary['coordinates'][0][0])
                        if center:
                            farm.latitude = center[0]
                            farm.longitude = center[1]
                else:
                    farm.lot_boundary_geojson = None
                
                farm.updated_at = datetime.utcnow()
                db.session.commit()
                
                logger.info(f"[EDIT_FARM] Farm {farm_id} updated successfully")
                flash(f'Farm "{farm.name}" updated successfully!', 'success')
                return redirect(url_for('farm.view_farm', farm_id=farm.id))
                
            except Exception as e:
                logger.error(f"[EDIT_FARM] POST ERROR: {str(e)}", exc_info=True)
                db.session.rollback()
                flash(f'Error updating farm: {str(e)}', 'error')
                return render_template('farm/edit.html', farm=farm, user=user, victoria_barangays=VICTORIA_BARANGAYS)
        
        return render_template('farm/edit.html', farm=farm, user=user, victoria_barangays=VICTORIA_BARANGAYS)
        
    except Exception as e:
        logger.error(f"[EDIT_FARM] ERROR: {str(e)}", exc_info=True)
        flash(f'Error accessing farm: {str(e)}', 'error')
        return redirect(url_for('farm.list_farms'))

@farm_bp.route('/<int:farm_id>', methods=['GET'])
@login_required
def view_farm(farm_id):
    """View farm details"""
    try:
        logger.info(f"[VIEW_FARM] User {session.get('user_id')} viewing farm {farm_id}")
        
        farm = Farm.query.get_or_404(farm_id)
        user = User.query.get(session['user_id'])
        
        if not user:
            logger.error(f"[VIEW_FARM] User not found: {session.get('user_id')}")
            flash('User not found', 'error')
            return redirect(url_for('auth.login'))
        
        logger.info(f"[VIEW_FARM] Farm {farm_id} found: {farm.name}")
        return render_template('farm/detail.html', farm=farm, user=user)
        
    except Exception as e:
        logger.error(f"[VIEW_FARM] ERROR: {str(e)}", exc_info=True)
        flash(f'Error viewing farm: {str(e)}', 'error')
        return redirect(url_for('farm.list_farms'))

@farm_bp.route('/<int:farm_id>/delete', methods=['POST'])
@login_required
def delete_farm(farm_id):
    """Delete a farm (soft delete)"""
    try:
        logger.info(f"[DELETE_FARM] User {session.get('user_id')} deleting farm {farm_id}")
        
        farm = Farm.query.get_or_404(farm_id)
        user = User.query.get(session['user_id'])
        
        if not user:
            logger.error(f"[DELETE_FARM] User not found: {session.get('user_id')}")
            flash('User not found', 'error')
            return redirect(url_for('auth.login'))
        
        # Only owner or admin can delete
        if user.id != farm.owner_id and user.role not in ['system_admin', 'victoria_admin']:
            logger.warning(f"[DELETE_FARM] Unauthorized delete attempt - User {user.id} trying to delete farm {farm_id} (owner: {farm.owner_id})")
            flash('You can only delete your own farms', 'error')
            return redirect(url_for('farm.list_farms'))
        
        farm_name = farm.name
        farm.is_active = False
        db.session.commit()
        
        logger.info(f"[DELETE_FARM] Farm {farm_id} deleted successfully by user {user.id}")
        flash(f'Farm "{farm_name}" deleted successfully!', 'success')
        return redirect(url_for('farm.list_farms'))
        
    except Exception as e:
        logger.error(f"[DELETE_FARM] ERROR: {str(e)}", exc_info=True)
        flash(f'Error deleting farm: {str(e)}', 'error')
        return redirect(url_for('farm.list_farms'))


@farm_bp.route('/api/barangay-boundaries', methods=['GET'])
@login_required
def barangay_boundaries():
    """Serve pre-generated Victoria, Laguna barangay boundary GeoJSON (from OSM)."""
    global _barangay_cache

    # Use in-memory cache after first load
    if _barangay_cache is not None:
        return jsonify(_barangay_cache)

    geojson_path = os.path.normpath(os.path.join(os.path.dirname(__file__), '..', 'static', 'victoria_barangays.json'))

    if os.path.exists(geojson_path):
        try:
            with open(geojson_path, 'r', encoding='utf-8') as f:
                _barangay_cache = json_module.load(f)
            logger.info(f"[BOUNDARIES] Loaded {len(_barangay_cache.get('features', []))} barangay features from static file")
            return jsonify(_barangay_cache)
        except Exception as e:
            logger.warning(f"[BOUNDARIES] Failed to read static file: {e}")

    # Fallback: approximate equal grid (should not be reached if generate_barangays.py was run)
    logger.warning("[BOUNDARIES] Static GeoJSON not found — using fallback grid")
    LAT_S, LAT_N = 14.1824, 14.2650
    LON_W, LON_E = 121.2974, 121.3718
    lat_step = (LAT_N - LAT_S) / 3
    lon_step = (LON_E - LON_W) / 3
    grid = [
        (2,0,'Banca-Banca'), (2,1,'Masapang'), (2,2,'Nanhaya'),
        (1,0,'Daniw'),       (1,1,'Pagalangan'),(1,2,'San Benito'),
        (0,0,'San Felix'),   (0,1,'San Francisco'),(0,2,'San Roque'),
    ]
    features = []
    for row, col, name in grid:
        s = LAT_S + row * lat_step
        n = s + lat_step
        w = LON_W + col * lon_step
        e = w + lon_step
        features.append({
            'type': 'Feature',
            'properties': {'name': name},
            'geometry': {'type': 'Polygon', 'coordinates': [[[w,s],[e,s],[e,n],[w,n],[w,s]]]}
        })
    return jsonify({'type': 'FeatureCollection', 'features': features, 'source': 'fallback'})


@farm_bp.route('/map', methods=['GET'])
@login_required
def farm_map():
    """Interactive GIS map of all farms"""
    try:
        user = User.query.get(session['user_id'])
        if not user:
            return redirect(url_for('auth.login'))
        return render_template('farm/map.html', user=user, barangays=VICTORIA_BARANGAYS)
    except Exception as e:
        logger.error(f"[FARM_MAP] ERROR: {str(e)}", exc_info=True)
        flash(f'Error loading map: {str(e)}', 'error')
        return redirect(url_for('farm.list_farms'))


@farm_bp.route('/api/geojson', methods=['GET'])
@login_required
def farms_geojson():
    """Return farms as GeoJSON FeatureCollection for Leaflet map"""
    try:
        user = User.query.get(session['user_id'])
        if not user:
            return jsonify({'error': 'Not authenticated'}), 401

        # Role-based filtering
        if user.role == 'farmer':
            farms = Farm.query.filter_by(owner_id=user.id, is_active=True).all()
        else:
            farms = Farm.query.filter_by(is_active=True).all()

        features = []
        unmapped = []

        for farm in farms:
            livestock_count = Livestock.query.filter_by(farm_id=farm.id).count()
            crop_count = Crop.query.filter_by(farm_id=farm.id).count()

            geometry = None
            boundary_geom = None
            if farm.lot_boundary_geojson:
                try:
                    boundary_geom = json_module.loads(farm.lot_boundary_geojson)
                except Exception:
                    boundary_geom = None

            props = {
                'id': farm.id,
                'name': farm.name,
                'barangay': farm.barangay_name or 'Unknown',
                'crop_type': farm.crop_type or 'N/A',
                'owner': farm.owner.full_name if farm.owner else 'Unknown',
                'livestock_count': livestock_count,
                'crop_count': crop_count,
                'area_sqm': farm.area_square_meters,
                'url': url_for('farm.view_farm', farm_id=farm.id),
                'has_location': bool(farm.latitude and farm.longitude),
                'has_boundary': bool(boundary_geom)
            }

            if boundary_geom:
                geometry = boundary_geom
            elif farm.latitude and farm.longitude:
                geometry = {'type': 'Point', 'coordinates': [farm.longitude, farm.latitude]}

            if geometry:
                features.append({
                    'type': 'Feature',
                    'geometry': geometry,
                    'properties': props
                })
            else:
                unmapped.append(props)

        return jsonify({
            'type': 'FeatureCollection',
            'features': features,
            'unmapped': unmapped,
            'total_farms': len(farms),
            'mapped_farms': len(features),
            'unmapped_farms': len(unmapped)
        })

    except Exception as e:
        logger.error(f"[FARMS_GEOJSON] ERROR: {str(e)}", exc_info=True)
        return jsonify({'error': str(e)}), 500
